Hec.Web/Areas/Admin/Controllers/TipCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Hec.Entities;
using Hec.Web.Controllers;
using System.Threading.Tasks;
using Hec.FileStorage;
using System.IO;

namespace Hec.Web.Areas.Admin.Controllers
{
    public class TipCategoryModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string FileId { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public int? FileSize { get; set; }

        public TipCategoryModel()
        {
        }

        public TipCategoryModel(TipCategory entity)
        {
            this.Id = entity.Id;
            this.Name = entity.Name;
            this.IsActive = entity.IsActive;
            this.FileId = entity.FileId;
            this.FileName = entity.FileName;
            this.FileExtension = entity.FileExtension;
            this.FileSize = entity.FileSize;
        }
    }

    [Authorize]
    public class TipCategoryController : BaseController
    {
        private IFileStore fileStore;

        public TipCategoryController(HecContext db, IFileStore fileStore) : base(db)
        {
            this.fileStore = fileStore;
        }

        public ActionResult Index()
        {
            ViewBag.Title = "Tips Categories";
            return View();
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<TipCategory> announcements = db.TipCategories;
            DataSourceResult result = announcements.ToDataSourceResult(request, entity => new {
                Id = entity.Id,
                Name = entity.Name,
                IsActive = entity.IsActive,
                FileId = entity.FileId,
                FileName = entity.FileName,
                FileExtension = entity.FileExtension,
                FileSize = entity.FileSize
            });

            return Json(result);
        }

        public ActionResult Create()
        {
            return View(new TipCategoryModel());
        }

        private static readonly Object createLock = new Object();
        private static readonly Object updateLock = new Object();

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public ActionResult Create([DataSourceRequest]DataSourceRequest request, [Bind(Exclude = "CreatedOn, UpdatedOn")] TipCategory tipCategory)
        {
            if (ModelState.IsValid)
            {
                lock (createLock)
                {
                    if (db.TipCategories.Any(x => x.Name == tipCategory.Name))
                        ModelState.AddModelError("Name", "TipCategory with name '" + tipCategory.Name + "' already existed.");
                    else
                    {
                        var entity = new TipCategory
                        {
                            Id = tipCategory.Id,
                            Name = tipCategory.Name,
                            IsActive = tipCategory.IsActive
                        };

                        if (!String.IsNullOrEmpty(tipCategory.FileId))
                        {
                            var stream = fileStore.GetStream(tipCategory.FileId);
                            fileStore.Delete(tipCategory.FileId);

                            var bytes = FileHelper.ReadBytes(stream);

                            var fileStream = new FileStream(BuildFileName(tipCategory.Name), FileMode.Create);
                            fileStream.Write(bytes, 0, bytes.Length);
                            fileStream.Flush();
                            fileStream.Close();

                            fileStore.Delete(tipCategory.FileId);
                        }

                        db.TipCategories.Add(entity);
                        db.SaveChanges();

                        tipCategory.Id = entity.Id;
                    }
                }
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            TipCategory entity = await db.TipCategories.FindAsync(id);
            if (entity == null)
            {
                return HttpNotFound();
            }

            return View(new TipCategoryModel(entity));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(Guid id, TipCategoryModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = await db.TipCategories.FindAsync(id);
                if (entity == null)
                {
                    return HttpNotFound();
                }
                
                if (!String.IsNullOrEmpty(model.FileId))
                {
                    var stream = fileStore.GetStream(model.FileId);
                    var bytes = FileHelper.ReadBytes(stream);

                    var fileStream = new FileStream(BuildFileName(entity.Name), FileMode.Create);
                    fileStream.Write(bytes, 0, bytes.Length);
                    fileStream.Flush();
                    fileStream.Close();

                    fileStore.Delete(model.FileId);
                }

                if (entity.Name != model.Name)
                {
                    var fi = new FileInfo(BuildFileName(entity.Name));
                    if (fi.Exists)
                    {
                        fi.MoveTo(BuildFileName(model.Name));
                    }
                }

                entity.Name = model.Name;
                entity.IsActive = model.IsActive;

                db.SetModified(entity);

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        private string BuildFileName(string name)
        {
            return Server.MapPath("~/Uploads/TipCategory/" + name + ".png");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> Delete(Guid id)
        {
            if (ModelState.IsValid)
            {
                var entity = await db.TipCategories.FindAsync(id);
                if (entity == null)
                {
                    return HttpNotFound();
                }

                db.SetDeleted(entity);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return RedirectToAction("Details", new { id = id });
        }

        //public ActionResult GetImage(Guid id)
        //{

        //    var stream = fileStore.GetStream(id);
        //    var fileName = System.IO.Path.GetFileName(fileId);

        //    return File(stream, System.Web.MimeMapping.GetMimeMapping(fileName), fileName);


        //    TipCategory obj = mms.GetMember(id);
        //    byte[] imageData = obj.FileSize;
        //    return File(imageData, "image/jpg");


        //    var imgquery = (from img in db.TipCategories
        //                    where img.Id == id

        //                    select new
        //                    {
        //                        Image = img.FileId
        //                    }).FirstOrDefault();
        //    {
        //        System.IO.MemoryStream outStream = new System.IO.MemoryStream();
        //        byte[] Image = imgquery.Image;
        //        return File(Image, "Image/jpg");
        //    }
        //}


        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Hec.Web/Areas/Admin/Views/TipCategory/Create.cshtml
@using Hec.Entities
@model Hec.Web.Areas.Admin.Controllers.TipCategoryModel

@{
    ViewBag.Title = "Title";
    ViewBag.BodyClass = "skin-blue sidebar-mini appliance-store";
    ViewBag.ActiveClass = "Categories";
}

<section class="content-header">
    <h1>
        Create Category
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><span class="fa fa-home"></span></a></li>
        <li>@Html.ActionLink("Category", "Index", "TipCategory")</li>
        <li class="active"> @Html.ActionLink("New Category", "Create", "TipCategory")</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-8">
            <div class="box">
                <div class="box-body">
                    @using (Html.BeginForm("Create", "TipCategory", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.Partial("_Editable", Model)
                    }
                </div>

            </div>
        </div>
    </div>
</section>

Hec.Web/Areas/Admin/Views/TipCategory/Edit.cshtml
@using Hec.Entities
@model Hec.Web.Areas.Admin.Controllers.TipCategoryModel

@{
    ViewBag.Title = "Title";
    ViewBag.BodyClass = "skin-blue sidebar-mini appliance-store";
    ViewBag.ActiveClass = "Categories";
}

<section class="content-header">
    <h1>
        Edit Categories
    </h1>
    <ol class="breadcrumb">
        <li><a href="/"><span class="fa fa-home"></span></a></li>
        <li>@Html.ActionLink("Categories", "Index", "TipCategory")</li>
        <li class="active"> @Html.ActionLink("Edit Categories", "Edit", "TipCategory")</li>

    </ol>
</section>


<section class="content">
    <div class="row">
        <div class="col-sm-8">
            <div class="box">
                <div class="box-body">
                    @using (Html.BeginForm("Edit", "TipCategory", FormMethod.Post))
                    {
                        @Html.Partial("_Editable", Model)
                    }
                </div>
            </div>
        </div>
    </div>
</section>

Hec.Web/Areas/Admin/Views/TipCategory/Index.cshtml
@{
    ViewBag.Title = "Manage Tip Categories";
    ViewBag.BodyClass = "skin-blue sidebar-mini appliance-store";
    ViewBag.ActiveClass = "Categories";
}

<section class="content-header">
    <h1>
        @ViewBag.Title
    </h1>
    <ol class="breadcrumb">
        <li><a href="~/Home/Index"><span class="fa fa-home"></span></a></li>
        <li class="active"> @Html.ActionLink("Tip Categories", "Index", "TipCategory")</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-sm-12">
            <div class="box grid-container">
                @(Html.Kendo().Grid<Hec.Entities.TipCategory>()
                  .Name("grid")
                  .Columns(columns =>
                  {
                  columns.Bound(c => c.Name);

                  columns.ForeignKey(c => c.IsActive, new SelectList(new List<SelectListItem>
                    {
                        new SelectListItem { Text = "Inactive", Value = bool.FalseString },
                        new SelectListItem { Text = "Active", Value = bool.TrueString },
                    }, "Value", "Text")).ClientTemplate("#: IsActive == true ? 'Active' : 'Inactive' #").Title("Status").Width(100);

                  columns.Template(@<text></text>).ClientTemplate("<img src='/Uploads/TipCategory/#= Name #.png' style='height:50px;width:50px;' />").Title("Icon").Width(100);
                  columns.Template(@<text></text>).ClientTemplate("<div class=\"btn btn-default\">" + "<a href='" + Url.Action("Edit", "TipCategory") + "/#=Id#'>Edit</a>").Title("Action").Width(70);
                  //columns.Command(command => { command.Destroy(); }).Width(50);
                  })
                  .ToolBar(toolbar =>
                  {
                      toolbar.Custom().Text("Create New Category").Action("Create", "TipCategory");
                  })
                  .Filterable(filterable => filterable
                      .Extra(false)
                      .Operators(operators => operators
                        .ForString(str => str.Clear()
                            .Contains("Contains with")
                        ))
                  )
                  .Editable(editable => editable.Mode(GridEditMode.InLine))
                  .Pageable()
                  .Navigatable()
                  .Selectable(selectable =>
                  {
                      selectable.Mode(GridSelectionMode.Single);
                      selectable.Type(GridSelectionType.Row);
                  })
                  .Sortable(sortable =>
                  {
                      sortable.SortMode(GridSortMode.SingleColumn);
                  })
                  .Scrollable(s => s.Height("auto"))
                  .DataSource(dataSource => dataSource
                      .Ajax()
                      .PageSize(10)
                      .Model(model =>
                      {
                          model.Id(p => p.Id);
                          model.Field(p => p.Name).Editable(false);
                      })
                      .Read(read => read.Action("Read", "TipCategory"))
                      .Destroy(destroy => destroy.Action("Delete", "TipCategory"))
                  )
                  .Events(events =>
                  {
                      events.FilterMenuInit("filterMenuInit");
                  })
                )
            </div>
        </div>
    </div>
</section>

@section Scripts
{
    <script>
    function filterMenuInit(e) {
        if (e.field == "PublishedOn") {
            var beginOperator = e.container.find("[data-role=dropdownlist]:eq(0)").data("kendoDropDownList");
            beginOperator.value("gte");
            beginOperator.trigger("change");

            var endOperator = e.container.find("[data-role=dropdownlist]:eq(2)").data("kendoDropDownList");
            endOperator.value("lte");
            endOperator.trigger("change");

            e.container.find(".k-filter-help-text").hide();
            e.container.find(".k-dropdown").hide();
            e.container.find(".k-datepicker:eq(0)").before("<div>From</div>");
            e.container.find(".k-datepicker:eq(1)").before("<div>To</div>");
        }
    }
    </script>
}

Hec.Web/Areas/Admin/Views/TipCategory/_Editable.cshtml
@using Hec.Entities
@model Hec.Web.Areas.Admin.Controllers.TipCategoryModel

<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-sm-3" })
        <div class="col-sm-9">
            @(Html.Kendo().TextBoxFor(model => model.Name))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-sm-3" })
        <div class="col-sm-9">
            @(Html.Kendo().CheckBoxFor(model => model.IsActive))
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Upload Image", htmlAttributes: new { @class = "control-label col-sm-3" })
        <div class="col-sm-9">
            <div style="width:94%">
                @(Html.Kendo().Upload()
                            .Name("file")
                            .Multiple(false)
                            .Async(a => a
                                .Save("Upload", "File", new { area = "" })
                                .Remove("Remove", "File", new { area = "" })
                                .AutoUpload(true)
                            )
                            .Multiple(false)
                            .Files(files =>
                            {
                                if (!String.IsNullOrEmpty(Model.FileId))
                                {
                                    files.Add().Name(Model.FileName)
                                        .Extension(Model.FileExtension)
                                        .Size(Model.FileSize.HasValue ? Model.FileSize.Value : 0);
                                }
                            })
                            .Events(events =>
                            {
                                events.Select("uploadSelect");
                                events.Success("uploadSuccess");
                                events.Remove("uploadRemove");

                            })
                            .Validation(validation => validation.AllowedExtensions(new string[] { ".jpg", ".png" }))
                )


                @Html.HiddenFor(m => m.FileId)
                @Html.HiddenFor(m => m.FileName)
                @Html.HiddenFor(m => m.FileExtension)
                @Html.HiddenFor(m => m.FileSize)

                <script>
                    function uploadSelect(e) {
                        $.each(e.files, function (index, value) {

                            var fileReader = new FileReader();
                            fileReader.onload = function (event) {
                                console.log(event);
                                var mapImage = event.target.result;
                                $("#preview").attr('src', mapImage);
                            }
                            fileReader.readAsDataURL(e.files[0].rawFile);

                            //Check file size. File size more than 2 MB is not allowed.
                            if (value.size > 2097152) {
                                e.preventDefault();
                                alert("File size more than 2 MB is not allowed.");
                                return false;
                            }

                        });
                    }

                    function uploadSuccess(e) {
                        if (e.operation == "upload") {
                            $("#FileId").val(e.response.fileId);
                            $("#FileName").val(e.response.fileName);
                            $("#FileExtension").val(e.response.fileExtension);
                            $("#FileSize").val(e.response.fileSize);

                            for (var i = 0; i < e.files.length; i++) {
                                var file = e.files[i].rawFile;

                                if (file) {
                                    var reader = new FileReader();

                                    reader.onloadend = function () {
                                        $("<div class='preview'><img width=50px height=50px src=" + this.result + " /></div>").appendTo($("#preview"));
                                    };

                                    reader.readAsDataURL(file);
                                }
                            }
                        }
                    }

                    function uploadRemove(e) {
                        var fileName = $("#FileId").val();
                        var fileId = $("#FileName").val();

                        $.ajax({
                            url: "@Url.Action("RemoveOnly", "File", new { area = "" })",
                            method: "POST",
                            data: {
                                fileId: fileId,
                            },
                            success: function (data, textStatus, jqXHR) {
                                $("#preview").html("");
                            }
                            //NOTE: Silent success/error
                        });

                        $("#FileId").val(null);
                        $("#FileName").val(null);
                        $("#FileExtension").val(null);
                        $("#FileSize").val(null);
                    }
                </script>
                <div class="help-text">Note: Best fit size is dimensions 53x53.</div>
                <br />

                
                    @if (Model.Name == null)
                    {
                        <div class="form-group" id="preview">
                            <div src="@Url.Content("~/Uploads/TipCategory/" + Model.Name + ".png")" alt="Image" @*style='height:50px;width:50px;'*@ />
                        </diV>
                    }
                    else
                    {
                        <div class="form-group" id="preview">
                            <img src="@Url.Content("~/Uploads/TipCategory/" + Model.Name + ".png")" alt="Image" @*style='height:50px;width:50px;'*@ />
                        </div>
                     }

                 </div>

            <div>@Html.ValidationMessageFor(model => model.FileId)</div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <input type="submit" value="Save" class="btn btn-primary col-sm-4" />
        </div>
    </div>
</div>