Hec.Web/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hec.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Hec.Web/Areas/Admin/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hec;
using Hec.Entities;
using Hec.Web.Controllers;

namespace Hec.Web.Areas.Admin.Controllers
{
    public class RoleList
    {
        public IEnumerable<string> AllAccessRights { get; set; }
        public IEnumerable<RoleListItem> Roles { get; set; }
    }

    public class RoleListItem
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public IEnumerable<RoleListItemAccessRight> AccessRights { get; set; }
    }

    public class RoleListItemAccessRight
    {
        public string Name { get; set; }
        public bool Assigned { get; set; }
    }

    public class UpdateAccessRightModel
    {
        public Guid RoleId { get; set; }
        public AccessRights AccessRight { get; set; }
        public bool Assigned { get; set; }
    }

    [Authorize]
    public class RolesController : BaseController
    {
        public RolesController(HecContext db) : base(db)
        {
        }

        public ActionResult Index()
        {
            var allAccessRights = Enum.GetValues(typeof(AccessRights)).Cast<AccessRights>();

            var roleList = new RoleList()
            {
                AllAccessRights = allAccessRights.Select(x => x.ToString()),
                Roles = new List<RoleListItem>()
            };

            db.Roles.OrderBy(x => x.Name).ToList().ForEach(x =>
            {
                var role = new RoleListItem
                {
                    Id = x.Id,
                    Name = x.Name,
                    AccessRights = new List<RoleListItemAccessRight>()
                };

                foreach (var accessRight in allAccessRights)
                {
                    ((List<RoleListItemAccessRight>) role.AccessRights).Add(
                        new RoleListItemAccessRight
                        {
                            Name = accessRight.ToString(),
                            Assigned = x.HaveAccessRight(accessRight)
                        }
                    );
                }

                ((List<RoleListItem>) roleList.Roles).Add(role);
            });

            return View(roleList);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> UpdateAccessRight(UpdateAccessRightModel model)
        {
            if (!ModelState.IsValid)
                return Status(HttpStatusCode.BadRequest);

            var role = db.Roles.Find(model.RoleId);
            if (role == null)
                throw new IdNotFoundException<Role>(model.RoleId);

            if (model.Assigned)
                role.AddAccessRight(model.AccessRight);
            else
                role.RemoveAccessRight(model.AccessRight);

            db.Entry(role).State = EntityState.Modified;

            await db.SaveChangesAsync();

            //System.Threading.Thread.Sleep(1000);
            return Ok();
        }

        //// GET: Roles/Details/5
        //public async Task<ActionResult> Details(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Role role = await db.Roles.FindAsync(id);
        //    if (role == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(role);
        //}

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Exclude= "Id")] Role role)
        {
            if (ModelState.IsValid)
            {
                role.Id = Guid.NewGuid();
                db.Roles.Add(role);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Role role = await db.Roles.FindAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                var entity = await db.Roles.FindAsync(role.Id);
                if (entity == null)
                    return NotFound();

                entity.Name = role.Name;
                entity.NeedZone = role.NeedZone;
                entity.NeedSubZone = role.NeedSubZone;
                entity.NeedUnit = role.NeedUnit;

                //db.Entry(role).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        //// GET: Roles/Delete/5
        //public async Task<ActionResult> Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Role role = await db.Roles.FindAsync(id);
        //    if (role == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(role);
        //}

        //// POST: Roles/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(Guid id)
        //{
        //    Role role = await db.Roles.FindAsync(id);
        //    db.Roles.Remove(role);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hec.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Hec.Entities;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Hec.Web.Controllers;
//using Hec.Web.Controllers;

namespace Hec.Web.Areas.Admin.Controllers
{
    public class UserDetail
    {
        public string Id { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string OfficeNumber { get;  set;}
        public string PhoneNumber { get; set; }
        public string Photo { get; set; }
        public LoginType LoginType { get; set; }
        public DateTime LastLogin { get; set; }
        public bool IsActive { get; set; }
        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string Designation { get; set; }
        public string Department { get; set; }
    }

    public class UserGridItem
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public LoginType LoginType { get; set; }
        public DateTime LastLogin { get; set; }
        public bool IsActive { get; set; }
        public string RoleName { get; set; }
    }

    [Authorize]
    public class UsersController : BaseController
    {
        private UserManager<User> userManager;

        public UsersController(HecContext db, UserManager<User> userManager) : base(db)
        {
            this.userManager = userManager;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest]DataSourceRequest request)
        {
            IQueryable<User> users = db.Users.Include(x => x.Role).Where(x => x.Role.Name == RoleNames.Administrator); // Admin only!
            DataSourceResult result = users.Select(x => new UserGridItem
                                        {
                                            Id = x.Id,
                                            UserName = x.UserName,
                                            LoginType = x.LoginType,
                                            LastLogin = x.LastLogin,
                                            FullName = x.FullName,
                                            IsActive = x.IsActive,
                                            RoleName = x.Role.Name

                                        })
                                        .ToDataSourceResult(request);

            return Json(result);
        }

        public async Task<ActionResult> Detail(string id)
        {
            var entity = await db.Users
                        //.Include(x => x.Role)
                        .FirstOrDefaultAsync(x => x.Id == id);

            if (entity == null)
                throw new IdNotFoundException<User>(id);

            return Json(new UserDetail
            {
                Id = entity.Id,
                UserName = entity.UserName,
                FullName = entity.FullName,
                Email = entity.Email,
                OfficeNumber = entity.OfficeNumber,
                PhoneNumber = entity.PhoneNumber,
                Photo = entity.Photo,
                LoginType = entity.LoginType,
                LastLogin = entity.LastLogin,
                IsActive = entity.IsActive,
                Designation = entity.Designation,
                Department = entity.Department,
                RoleId = entity.RoleId
            });
        }

        public ActionResult Edit(string id)
        {
            CheckAccess(AccessRights.SuperUser);

            return View((object)id);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> Update(string id, UserDetail model)
        {
            CheckAccess(AccessRights.SuperUser);

            if (!ModelState.IsValid)
            {
                return Status(HttpStatusCode.BadRequest);
            }

            if (id != model.Id)
            {
                return Status(HttpStatusCode.BadRequest);
            }

            var entity = await db.Users
                    .FirstOrDefaultAsync(x => x.Id == id);

            if (entity == null)
                throw new IdNotFoundException<User>(id);

            entity.FullName = model.FullName;
            entity.Email = model.Email;
            entity.OfficeNumber = model.OfficeNumber;
            entity.PhoneNumber = model.PhoneNumber;
            entity.Photo = model.Photo;
            entity.LoginType = model.LoginType;
            entity.LastLogin = model.LastLogin;
            entity.Designation = model.Designation;
            entity.Department = model.Department;
            entity.IsActive = model.IsActive;
            entity.RoleId = model.RoleId;

            db.SetModified(entity);
            await db.SaveChangesAsync();

            return Json(model);
        }

        public ActionResult Create()
        {
            CheckAccess(AccessRights.SuperUser);

            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> Create(UserDetail model)
        {
            CheckAccess(AccessRights.SuperUser);

            if (!ModelState.IsValid)
            {
                return Status(HttpStatusCode.BadRequest);
            }

            var existing = await db.Users.FirstOrDefaultAsync(x => x.UserName == model.UserName);
            if (existing != null)
                throw new Exception("Username already exists.");

            var entity = new User();
            entity.Id = entity.UserName = model.UserName;
            entity.FullName = model.FullName;
            entity.Email = model.Email;
            entity.OfficeNumber = model.OfficeNumber;
            entity.PhoneNumber = model.PhoneNumber;
            entity.Photo = model.Photo;
            entity.LoginType = model.LoginType;
            entity.Designation = model.Designation;
            entity.Department = model.Department;
            entity.RoleId = model.RoleId;

            if (model.LoginType == LoginType.Internal)
            {
                entity.PasswordHash = userManager.PasswordHasher.HashPassword(model.Password);
            }

            db.Users.Add(entity);
            await db.SaveChangesAsync();

            model.Id = entity.Id;
            return Json(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> Destroy(Guid key)
        {
            CheckAccess(AccessRights.SuperUser);

            var entity = db.Users.Find(key);
            if (entity == null)
            {
                return Status(HttpStatusCode.NotFound);
            }

            db.SetDeleted(entity);
            await db.SaveChangesAsync();

            return Ok();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ChangePassword(string id)
        {
            CheckAccess(AccessRights.SuperUser);
            return View((object)id);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public async Task<ActionResult> ChangePassword(string userId, string password)
        {
            CheckAccess(AccessRights.SuperUser);

            if (!ModelState.IsValid)
            {
                return Status(HttpStatusCode.BadRequest);
            }

            var user = db.Users.Find(userId);
            if (user == null)
                throw new IdNotFoundException<User>(userId);

            user.PasswordHash = userManager.PasswordHasher.HashPassword(password);
            db.SetModified(user);
            await db.SaveChangesAsync();

            return Ok();
        }
    }
}

Hec.Web/Areas/Public/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hec.Web.Areas.Public.Controllers
{
    public class HomeController : Web.Controllers.BaseController
    {
        public HomeController(HecContext db) : base(db)
        {
        }

        // GET: Public/Home
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "BillInfo");
            }
            else
            {
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            //return View();
            //return RedirectToAction("Index", "BillInfo");
        }

        [HttpGet]
        public ActionResult ChangePhoto()
        {
            return View();
        }

        public ActionResult ProfilePhoto()
        {
            if (!User.Identity.IsAuthenticated)
                return Content("");

            var user = GetCurrentUser();
            if (String.IsNullOrEmpty(user.Photo))
                return Content("");

            return Content($"<img src='{user.Photo}' />");
        }

        public ActionResult ChangePhoto(HttpPostedFileBase file)
        {
            if (file == null)
            {
                ViewBag.ErrorMessage = "Please select a file.";
                return View();
            }

            var extension = Path.GetExtension(file.FileName).ToLower();
            if (extension != ".jpg" && extension != ".jpeg")
            {
                ViewBag.ErrorMessage = "Only JPG file is allowed.";
                return View();
            }

            if (file.ContentLength > 500000)
            {
                ViewBag.ErrorMessage = "File must be less than 500kB in size.";
                return View();
            }
            
            if (User.Identity.IsAuthenticated)
            {
                var user = db.Users.Find(User.Identity.Name);
                if (user != null)
                {
                    var bytes = FileStorage.FileHelper.ReadBytes(file.InputStream);
                    user.Photo = "data:image/png;base64," + Convert.ToBase64String(bytes);
                    db.SetModified(user);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }
    }
}

Hec.Web/Views/Home/Features.cshtml
<body class="one-page" data-target=".single-menu" data-spy="scroll" data-offset="200">

    <div class="body">
        <header id="header" class="single-menu flat-menu transparent valign font-color-light" data-plugin-options='{"stickyEnabled": true, "stickyBodyPadding": false}'>
            <div class="container">
                <div class="logo">
                    <a href="@(Url.Action("Index", "Home", new { area = "" }))" class="logo">
                        <img alt="Porto" width="111" height="54" data-sticky-width="82" data-sticky-height="40" src="~/Images/logo-hec.png">
                    </a>
                </div>
                <button class="btn btn-responsive-nav btn-inverse" data-toggle="collapse" data-target=".nav-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <div class="navbar-collapse nav-main-collapse collapse">
                <div class="container">
                    <ul class="social-icons">
                        <li class="dribbble"><a href="https://www.mytnb.com.my/" target="_blank" title="MyTNB Customer Portal">MyTNB</a></li>
                        <li class="digg"><a href="https://www.tnb.com.my/" target="_blank" title="TNB Website">TNB Website</a></li>
                    </ul>

                    <nav class="nav-main mega-menu">
                        <ul class="nav nav-pills nav-main" id="mainMenu">
                            <li class="active">
                                <a href="/">Home</a>
                            </li>
                            <li>
                                <a href="/Public/UsageCalculator">Energy Usage Calculator </a>
                            </li>
                            <li>
                                <a href="/Public/EnergyTips">Energy Tips </a>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="/Public/ApplianceComparison">Appliance Calculator <i class="fa fa-angle-down"></i></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/Public/ApplianceComparison/SingleAppliance">Single Appliance</a></li>
                                    <li><a href="/Public/ApplianceComparison/CompareAppliance">Compare Appliances</a></li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>

        <div role="main" class="main">
            <div class="slider-container slider-container-fullscreen">
                <div class="slider" id="revolutionSliderFullScreen" data-plugin-revolution-slider data-plugin-options='{"fullScreen": "on"}'>
                    <ul>

                        <li data-transition="fade" data-slotamount="10" data-masterspeed="300">
                            <img src="~/Images/features/BG_Features.jpg" data-fullwidthcentering="on" alt="">

                            <div class="tp-caption sft stb visible-lg"
                                 data-x="467"
                                 data-y="160"
                                 data-speed="300"
                                 data-start="1000"
                                 data-easing="easeOutExpo"><img src="~/Images/slides/slide-title-border.png" alt=""></div>

                            <div class="tp-caption top-label lfl stl"
                                 data-x="center" data-hoffset="0"
                                 data-y="160"
                                 data-speed="300"
                                 data-start="500"
                                 data-easing="easeOutExpo">EXPLORE</div>

                            <div class="tp-caption sft stb visible-lg"
                                 data-x="667"
                                 data-y="160"
                                 data-speed="300"
                                 data-start="1000"
                                 data-easing="easeOutExpo"><img src="~/Images/slides/slide-title-border.png" alt=""></div>

                            <div class="tp-caption main-label sft stb"
                                 data-x="center" data-hoffset="0"
                                 data-y="180"
                                 data-speed="300"
                                 data-start="1500"
                                 data-easing="easeOutExpo">HEC FEATURES</div>

                            <div class="tp-caption bottom-label sft stb"
                                 data-x="center" data-hoffset="0"
                                 data-y="240"
                                 data-speed="500"
                                 data-start="2000"
                                 data-easing="easeOutExpo">Check out our new features.</div>


                        </li>



                    </ul>
                </div>
            </div>


        </div>

        <br /><br />
        <div class="container" style="display:none;">

            <div class="row center">
                <div class="col-md-12">
                    <h1 class="short word-rotator-title" style="font-size:22px;">
                        Your Best <b>Advisor </b>for
                        <strong class="inverted" data-appear-animation="bounceIn">
                            <span class="word-rotate" data-plugin-options='{"delay": 2000}'>
                                <span class="word-rotate-items">
                                    <span>Energy Usage Calculator</span>
                                    <span>Energy Saving Tips</span>
                                    <span>Appliance Calculator</span>
                                </span>
                            </span>
                        </strong>
                    </h1>
                    <p class="featured lead" style="font-size:20px;">
                        Since you’re at the heart of everything we do, we’d like to lighten the load by helping you save with useful energy efficiency tips.
                        Everything to help you save and be more efficient, while being greener and kinder to the earth.
                    </p>
                </div>
            </div>

        </div>

        <section style=" ">
            <div class="container">
                <div class="row center">
                    <div class="col-md-4">
                        <img src="~/Images/features/savingtips_01.jpg" style="float:left;" />
                    </div>
                    <div class="col-md-8">
                        <h1 class="short word-rotator-title" style="font-size:20px;padding-top:80px;">
                            Your Best <b>Advisor </b>for
                            <strong class="inverted" data-appear-animation="bounceIn">
                                <span class="word-rotate" data-plugin-options='{"delay": 2000}'>
                                    <span class="word-rotate-items">
                                        <span>Energy Usage Calculator</span>
                                        <span>Energy Saving Tips</span>
                                        <span>Appliance Calculator</span>
                                    </span>
                                </span>
                            </strong>
                        </h1>
                        <p class="featured lead" style="font-size:18px;">
                            Since you’re at the heart of everything we do, we’d like to lighten the load by helping you save with useful energy efficiency tips.Everything to help you save and be more efficient, while being greener and kinder to the earth.
                        </p>
                    </div>
                </div>
            </div>
            <hr class="tall" />
        </section>

        <section style="background: url('/Images/features/Features_001.jpg') no-repeat;background-position:100%;background-size:70%; height:573px;">
            <div class="container">
                <div class="row center">
                    <div class="col-md-12">
                        <div class="col-md-12">
                            <h3 class="short " style="float:left;font-size:24px;color:#000;text-align:left;text-transform:none;line-height:1.5;">
                                How to <b style="font-style:italic;">reduce</b> your <b style="color:#09599b;">Monthly Energy Consumption?</b><br />
                                Let us guide you using our Appliance Calculator.
                            </h3>
                        </div>
                        <br /><br /><br />
                        <img src="~/Images/features/greendashboard_01.png" style="float:left;margin-left:-30px;" />

                    </div>
                </div>
            </div>
        </section>

        <section class="parallax" data-stellar-background-ratio="0.5" style="background-image: url('/Images/features/Features_002.jpg');background-position: 0% 30px;height:669px;">
            <div class="container">
                <div class="row center">
                    <div class="col-md-12">
                        <h3 class="short " style="float:right;font-size:24px;color:#000;text-align:right;text-transform:none;line-height:1.5;">
                            <b style="color:#09599b;">Compare with Friends</b> Energy Usage<br />
                            Share your Energy Saving Tips.
                        </h3>
                    </div>
                </div>
            </div>
        </section>

        <section style="background-image: url('/Images/features/Features_003.jpg');height:663px;">
            <div class="container">
                <div class="row center">
                    <div class="col-md-12">
                        <br /><br />
                        <h3 class="short " style="font-size:24px;color:#000;text-transform:none;line-height:1.5;">
                            Get updates on your Billing Info.<br />
                            <b>Register</b> with <a href="https://www.mytnb.com.my/" target="_blank" style="text-decoration:none;"><b style="color:#d0182a">myTNB</b></a> now!
                        </h3>
                    </div>
                </div>
            </div>
        </section>

    </div>
</body>

Hec.Web/Views/Home/_MainMenu.cshtml
@using Hec.Entities
@using Hec.Web.Controllers

@model Hec.Entities.User

<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu">
    <li class="header">NAVIGATION</li>
    <li class="treeview active">
        <a href="#">
            <i class="fa fa-pie-chart fa-lg"></i> <span> Reports</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
        </ul>
    </li>

    @if (Model.HaveAccessRight(AccessRights.SuperUser))
    {
    <li class="treeview active">
        <a href="#">
            <i class="fa fa-gears fa-lg"></i> <span> Settings</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="@(Url.Action("Index", "Users"))"><span class="fa fa-user"></span> Users</a></li>
            <li><a href="@(Url.Action("Index", "Roles"))"><span class="fa fa-users"></span> Roles</a></li>
            @*<li><a href="@(Url.Action("Index", "Zones"))"><span class="fa fa-flag"></span> Zones</a></li>
    <li><a href="@(Url.Action("Index", "SubZones"))"><span class="fa fa-flag-o"></span> Sub-Zones</a></li>
    <li><a href="@(Url.Action("Index", "Stations"))"><span class="fa fa-building"></span> Stations</a></li>
    <li><a href="@(Url.Action("Index", "SubStations"))"><span class="fa fa-building-o"></span> Sub-Stations (PE)</a></li>
    <li><a href="@(Url.Action("Index", "States"))"><i class="fa fa-globe"></i><span> State</span></a></li>
    <li><a href="@(Url.Action("Index", "Units"))"><span class="fa fa-briefcase"></span> Units</a></li>
    <li><a href="@(Url.Action("Index", "ShutdownReasons"))"><span class="fa fa-commenting"></span> Shutdown Reasons</a></li>*@
            <li><a href="@(Url.Action("Index", "TipCategories"))"><span class="fa fa-flash"></span> Tips Categories</a></li>
            <li><a href="@(Url.Action("Index", "Tips"))"><span class="fa fa-bullhorn"></span> Tips</a></li>
            <li><a href="@(Url.Action("Index", "EmailTemplate"))"><span class="fa fa-envelope-o"></span> Email Template</a></li>
            <li><a href="@(Url.Action("Index", "EmailQueue"))"><span class="fa fa-envelope"></span> Email Queue</a></li>
            @*<li><a href="@(Url.Action("Index", "SlaSettings"))"><i class="fa fa-clock-o"></i><span> SLA Settings</span></a></li>*@
            <li>@*<a href="@(Url.Action("Index", "OffDay"))"><i class="fa fa-calendar"></i><span> Off-Day Management</span></a>*@</li>
            @*<li><a href="@(Url.Action("Index", "HelpFiles"))"><i class="fa fa-book"></i><span> User Manuals</span></a></li>
            <li><a href="@(Url.Action("Index", "SystemSettings"))"><i class="fa fa-wrench"></i><span> System Configuration</span></a></li>*@
        </ul>
    </li>
    }
</ul>